namespace: stackhpc
name: slurmapp_ops
version: 0.0.1
description: Infrastructure provisioning and configuration of a Slurm platform using Ansible
readme: README.md
authors:
  - "Steve Brasier <steveb@stackhpc.com>"
  - "Matt Anson <matta@stackhpc.com>"
license:
  - "Apache-2.0"
repository: "https://github.com/stackhpc/ansible-slurm-appliance"

dependencies: {}